{% set name = "cythonbuilder" %}
{% set version = "0.1.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cythonbuilder-{{ version }}.tar.gz
  sha256: 7c8751d9b82aa2754a05ba3eb7e19b48672db2bc7ff4e6f6307c1db55d3bf6f1

build:
  noarch: python
  entry_points:
    - cythonbuilder=cythonbuilder.cli:main
    - cybuilder=cythonbuilder.cli:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - cython
    - coloredlogs

test:
  imports:
    - cythonbuilder
  commands:
    - pip check
    - cythonbuilder --help
    - cybuilder --help
  requires:
    - pip

about:
  home: https://github.com/mike-huls/cythonbuilder
  summary: CythonBuilder; automated compiling and packaging of Cython code
  dev_url: https://github.com/mike-huls/cythonbuilder/
  license: MIT
  license_file: license.txt

extra:
  recipe-maintainers:
    - pavelzw
