{% set name = "cythonbuilder" %}
{% set version = "0.1.15" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cythonbuilder-{{ version }}.tar.gz
  sha256: c6e92e83bf43f3de5cb1a5791136e5a3285b996d515133085ea4d50ca4077a69

build:
  noarch: python
  entry_points:
    - cythonbuilder=cythonbuilder.cli:main
    - cybuilder=cythonbuilder.cli:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - cython
    - coloredlogs

test:
  imports:
    - cythonbuilder
  commands:
    - pip check
    - cythonbuilder --help
    - cybuilder --help
  requires:
    - pip

about:
  home: https://github.com/mike-huls/cythonbuilder
  summary: CythonBuilder; automated compiling and packaging of Cython code
  dev_url: https://github.com/mike-huls/cythonbuilder/
  license: MIT
  license_file: license.txt

extra:
  recipe-maintainers:
    - pavelzw
